FROM gentoo/stage3-amd64
RUN mkdir /usr/portage; \
    emerge-webrsync; \
    eselect python set python2.7; \
    echo 'MAKEOPTS="-j4"' >> /etc/portage/make.conf; \
    USE="-*" emerge --autounmask-write \
                    dev-python/numpy \
                    dev-python/requests \
                    sci-mathematics/minisat \
    yes | etc-update --automode -3; \
    USE="-*" emerge --autounmask-write \
                    dev-python/numpy \
                    dev-python/requests \
                    sci-mathematics/minisat \
    easy_install satispy; \
    easy_install pycosat; \
    rm -rf /usr/portage;
COPY scripts/FlagGenerator/* /root/
COPY etc_portage/* /etc/portage/


# vim: ft=dockerfile :
